services:
  api:
    build: .
    container_name: pokemon_api
    restart: unless-stopped
    ports:
      - "8081:8001"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pokemon_images:/app/static/images
    networks:
      - pokemon-network

networks:
  pokemon-network:
    driver: bridge

volumes:
  pokemon_images: